Feature/footer
Krenichniy/swat-test pull request #18
Opened 2022-02-20 20:19 UTC by trofyna

feature/footer ,
thanks for help Team Lead and Lexk/87

2022-02-20 20:36 UTC, Krenichniy commented on src/partials/footer.html
> +            <p class="footer__contact">
здесь может див нужен? у тебя просто есть закрывающий див и открывающий п

2022-02-20 20:37 UTC, Krenichniy commented on src/partials/footer.html
> +            <p class="footer__contact">
лучше вкладывать в див спан и ссылку, п -используется для разметки абзаца текста

2022-02-20 20:40 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +      padding-bottom: 18px;
откуда такая цыфра?

2022-02-20 20:41 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +  @include font(18px,400,1.16, 0.04px);
вместо 0.04 значение null, здесь и в других местах исправить

2022-02-20 20:42 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +  color: #FEA5BB;
этот цвет есть в переменных

2022-02-20 20:43 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +    fill: #ffffff;
цвет есть в переменных

2022-02-20 20:43 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +    background-color: #FEA5BB;
переменная

2022-02-20 20:43 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +    background-color: #d41443;
цвет

2022-02-20 20:45 UTC, Krenichniy commented on src/sass/common/_footer.scss
> +  display: flex;
можно использовать миксин @include flex (flex, flex-end, null)

2022-02-20 20:46 UTC, Krenichniy requested changes
хорошая работа , но нужны правки)

2022-02-20 20:55 UTC, trofyna commented on src/partials/footer.html
> +            <p class="footer__contact">
когда мы обговорили  флекс для иконок + тел ,кот. в р> -они оборачиваются в див
т.е. 
есть 
ul>для - иконок
после него р>( входит спан>для текста  и  a> -ссылки в которой телефон)
и все это обернуто в див> футер -медиа 
еще див ?разве нужно

2022-02-20 20:56 UTC, trofyna commented on src/partials/footer.html
> +            <p class="footer__contact">
если по семантике нужно  я добавлю

2022-02-20 21:31 UTC, trofyna commented on src/partials/footer.html
> +            <p class="footer__contact">
- [ ] done

2022-02-20 21:33 UTC, trofyna commented on src/sass/common/_footer.scss
> +  @include font(18px,400,1.16, 0.04px);
done

2022-02-20 21:37 UTC, trofyna commented on src/sass/common/_footer.scss
> +  color: #FEA5BB;
![image](https://user-images.githubusercontent.com/64868442/154865315-db93c240-8fd5-4f6e-9eb6-feda07d751a6.png)
в 41 моей color: #FEA5BB;
в reset  --sub-title-color: #ffa5ba;

2022-02-20 21:42 UTC, trofyna commented on src/sass/common/_footer.scss
> +    fill: #ffffff;
done

2022-02-20 21:43 UTC, trofyna commented on src/sass/common/_footer.scss
> +    background-color: #FEA5BB;
fffff - done
#FEA5BB; - в переменных нет

2022-02-20 21:46 UTC, trofyna commented on src/sass/common/_footer.scss
> +    background-color: #d41443;
#ffffff; done
#d41443; done

2022-02-20 21:47 UTC, trofyna commented on src/sass/common/_footer.scss
> +  display: flex;
done

2022-02-21 06:39 UTC, Krenichniy approved these changes
хороша работа, спасибо)

2022-02-21 06:39 UTC, merged