Feature/modal contacts
Krenichniy/swat-test pull request #6
Opened 2022-02-19 10:37 UTC by irinakruchko

Готова модалка location-modal (є атрибути скріпта, без button-open). franchise comment. is-hidden закоментований (поки немає скріпта)

2022-02-19 11:10 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  @include min1200 {
тут виправ будь ласка на 1280пх

2022-02-19 11:11 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  @include min1200 {
тут так само 1280пх

2022-02-19 11:12 UTC, Krenichniy requested changes
внеси будь ласка маленькі правки

2022-02-20 18:15 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  @include min1200 {
Виправила

2022-02-20 18:15 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  @include min1200 {
Виправила

2022-02-20 18:35 UTC, Krenichniy commented on src/partials/modal-contacts.html
> +                            <label for="name" class="franchise-form__lable"> Имя <label />
неправильний закриваючий тег

2022-02-20 18:36 UTC, Krenichniy commented on src/partials/modal-contacts.html
> +                            <label for="tel" class="franchise-form__lable"> Телефон <label />
тут теж, спочатку / потім назва тегу

2022-02-20 18:36 UTC, Krenichniy commented on src/partials/modal-contacts.html
> +                            <label for="email" class="franchise-form__lable"> Почта <label />
тут також /

2022-02-20 18:41 UTC, Krenichniy commented on src/partials/modal-contacts.html
> +                            </label>
що він закриває?

2022-02-20 18:45 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  transition: transform 250ms;
допиши функцію будь-ласка, лінеар чи щось таке

2022-02-20 18:46 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  transform: scale(1, 1);
потрібно ще транзішн указати

2022-02-20 18:47 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-style: normal;
це в нас по дефолту, не потрібно писати

2022-02-20 18:47 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-family: Roboto;
цього шрифта в нас немає, мені додати?

2022-02-20 18:47 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-weight: normal;
тут 400

2022-02-20 18:48 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-size: 25px;
тут можна використати міксин наш

2022-02-20 18:48 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +    display: flex;
тут також можна міксин

2022-02-20 18:49 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +    font-size: 35px;
міксин

2022-02-20 18:49 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  display: flex;
міксин

2022-02-20 18:49 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-size: 14px;
міксин

2022-02-20 18:49 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  display: flex;
міксин

2022-02-20 18:50 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  fill: #fff;
в нас є цей колір в змінних

2022-02-20 18:50 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +    fill: #fff;
колір через змінну

2022-02-20 18:51 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +    color: #d41443;
через змінну

2022-02-20 18:51 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  color: #d41443;
змінна

2022-02-20 18:52 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +    fill: #d41342;
змінна

2022-02-20 18:52 UTC, Krenichniy commented on src/sass/common/_modal-contacts.scss
> +  font-size: 16px;
міксин

2022-02-20 18:53 UTC, Krenichniy requested changes
зроби зміни будь ласка)

2022-02-20 21:33 UTC, irinakruchko commented on src/partials/modal-contacts.html
> +                            <label for="name" class="franchise-form__lable"> Имя <label />
змінила

2022-02-20 21:33 UTC, irinakruchko commented on src/partials/modal-contacts.html
> +                            <label for="tel" class="franchise-form__lable"> Телефон <label />
змінила

2022-02-20 21:34 UTC, irinakruchko commented on src/partials/modal-contacts.html
> +                            <label for="email" class="franchise-form__lable"> Почта <label />
змінила

2022-02-20 21:34 UTC, irinakruchko commented on src/partials/modal-contacts.html
> +                            </label>
на локальному його не було, напевно видалила після коміту

2022-02-20 21:35 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  transition: transform 250ms;
додала анімацію

2022-02-20 21:35 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  font-style: normal;
прибрала

2022-02-20 21:35 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  font-family: Roboto;
замінила на інший

2022-02-20 21:35 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  font-weight: normal;
зробила

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  font-size: 25px;
є

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +    display: flex;
є

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  display: flex;
є

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  display: flex;
+

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +    fill: #fff;
зробила

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  color: #d41443;
є

2022-02-20 21:36 UTC, irinakruchko commented on src/sass/common/_modal-contacts.scss
> +  font-size: 16px;
є

2022-02-20 21:40 UTC, Krenichniy approved these changes

2022-02-20 21:41 UTC, merged